import { Metadata } from "next";

export const metadata: Metadata = {
    title: "Create Next App - About",
    description: "Generated by create next app",
};

export default function AboutLayoutt({
    children,
  }: Readonly<{
    children: React.ReactNode;
  }>) {
  return (
        <div>
            About Layout
            {children}
        </div>
    );
}